// Generated by CoffeeScript 1.6.3
(function(window) {
  var Colour, allColours, colourIndexLength, colourToIndex, lighterColour, randomColour, randomColours, randomColoursLength;
  Colour = {
    NONE: "#ffffff",
    RED: "#bb0000",
    GREEN: "#00bb00",
    BLUE: "#0000bb",
    YELLOW: "#bbbb00",
    LIGHT_RED: "#ff1010",
    LIGHT_GREEN: "#10ff10",
    LIGHT_BLUE: "#1010ff"
  };
  colourToIndex = {};
  colourToIndex[Colour.NONE] = 0;
  colourToIndex[Colour.RED] = 1;
  colourToIndex[Colour.GREEN] = 2;
  colourToIndex[Colour.BLUE] = 3;
  colourToIndex[Colour.YELLOW] = 4;
  colourToIndex[Colour.LIGHT_RED] = 5;
  colourToIndex[Colour.LIGHT_GREEN] = 6;
  colourToIndex[Colour.LIGHT_BLUE] = 7;
  allColours = [Colour.NONE, Colour.RED, Colour.GREEN, Colour.BLUE, Colour.YELLOW, Colour.LIGHT_RED, Colour.LIGHT_GREEN, Colour.LIGHT_BLUE, Colour.LIGHT_YELLOW];
  colourIndexLength = allColours.length;
  randomColours = [Colour.RED, Colour.GREEN, Colour.BLUE, Colour.YELLOW];
  randomColoursLength = randomColours.length;
  randomColour = function() {
    return randomColours[randomNumberExclusive(0, randomColoursLength)];
  };
  lighterColour = function(colour) {
    switch (colour) {
      case Colour.RED:
        return Colour.LIGHT_RED;
      case Colour.GREEN:
        return Colour.LIGHT_GREEN;
      case Colour.BLUE:
        return Colour.LIGHT_BLUE;
      case Colour.YELLOW:
        return Colour(LIGHT_YELLOW);
      default:
        return Colour.NONE;
    }
  };
  window.Colour = Colour;
  window.colourToIndex = colourToIndex;
  window.allColours = allColours;
  window.colourIndexLength = colourIndexLength;
  window.randomColour = randomColour;
  return window.lighterColour = lighterColour;
})(window);
