// Generated by CoffeeScript 1.6.3
(function(window) {
  var Key, clearKeys, i, isKeyDown, isKeyDownIn, isKeyUp, keys, onKeyDown, onKeyUp, previousKeys, updateKeys, wasKeyDown, wasKeyUp, _i;
  keys = [];
  previousKeys = [];
  for (i = _i = 0; _i <= 256; i = _i += 1) {
    keys[i] = false;
    previousKeys[i] = false;
  }
  onKeyDown = function(event) {
    if (event == null) {
      event = window.event;
    }
    return keys[event.keyCode] = true;
  };
  onKeyUp = function(event) {
    if (event == null) {
      event = window.event;
    }
    return keys[event.keyCode] = false;
  };
  updateKeys = function() {
    var _j, _ref;
    for (i = _j = 0, _ref = keys.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      previousKeys[i] = keys[i];
    }
    return null;
  };
  clearKeys = function() {
    var _j, _ref;
    for (i = _j = 0, _ref = keys.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      keys[i] = false;
      previousKeys[i] = false;
    }
    return null;
  };
  Key = {
    LEFT: [37, 65],
    RIGHT: [39, 68],
    DOWN: [40, 83],
    PAUSE: [80, 27]
  };
  isKeyDownIn = function(key, array) {
    var _j, _ref;
    for (i = _j = 0, _ref = key.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      if (array[key[i]]) {
        true;
      }
    }
    return false;
  };
  isKeyDown = function(key) {
    return isKeyDownIn(key, keys);
  };
  isKeyUp = function(key) {
    return !isKeyDownIn(key, keys);
  };
  wasKeyDown = function(key) {
    return isKeyDownIn(key, previousKeys);
  };
  wasKeyUp = function(key) {
    return !isKeyDownIn(key, previousKeys);
  };
  window.onKeyDown = onKeyDown;
  window.onKeyUp = onKeyUp;
  window.updateKeys = updateKeys;
  window.clearKeys = clearKeys;
  window.Key = Key;
  window.isKeyDown = isKeyDown;
  window.isKeyUp = isKeyUp;
  window.wasKeyDown = wasKeyDown;
  return window.wasKeyUp = wasKeyUp;
})(window);
