// Generated by CoffeeScript 1.6.3
(function(window) {
  var getMousePosition, getMouseX, getMouseY, isMouseDown, isMouseUp, mouse, mouseLetGo, onMouseDown, onMouseMove, onMouseUp, setMousePosition, updateMouse;
  mouse = {
    down: false,
    x: -1,
    y: -1
  };
  mouseLetGo = false;
  updateMouse = function() {
    if (mouseLetGo) {
      mouse.down = false;
      return mouseLetGo = false;
    }
  };
  getMousePosition = function(event) {
    var _ref, _ref1;
    return [(_ref = event.x) != null ? _ref : event.clientX + document.body.scrollLeft + document.documentElement.scrollLeft, -canvas.offsetLeft + canvasBorderThickness, (_ref1 = event.y) != null ? _ref1 : event.clientY + document.body.scrollTop + document.documentElement.scrollTop, -canvas.offsetTop + canvasBorderThickness];
  };
  setMousePosition = function(event) {
    var pos;
    if (event == null) {
      event = window.event;
    }
    pos = getMousePosition(event);
    mouse.x = pos[0];
    return mouse.y = pos[1];
  };
  onMouseDown = function(event) {
    if (event == null) {
      event = window.event;
    }
    mouse.down = true;
    return setMousePosition(event);
  };
  onMouseMove = function(event) {
    if (event == null) {
      event = window.event;
    }
    return setMousePosition(event);
  };
  onMouseUp = function(event) {
    if (event == null) {
      event = window.event;
    }
    mouseLetGo = true;
    return setMousePosition(event);
  };
  isMouseDown = function() {
    return mouse.down;
  };
  isMouseUp = function() {
    return !mouse.down;
  };
  getMouseX = function() {
    return mouse.x;
  };
  getMouseY = function() {
    return mouse.y;
  };
  window.updateMouse = updateMouse;
  window.onMouseDown = onMouseDown;
  window.onMouseMove = onMouseMove;
  window.onMouseUp = onMouseUp;
  window.isMouseDown = isMouseDown;
  window.isMouseUp = isMouseUp;
  window.getMouseX = getMouseX;
  return window.getMouseY = getMouseY;
})(window);
